/**
 * Export Service
 * Pure functions for generating PDF, DOCX, and TXT buffers.
 * No HTTP concerns — returns buffers and metadata.
 */

/**
 * Clean markdown formatting from content for export.
 * @param {string} content
 * @returns {string}
 */
function cleanMarkdown(content) {
  return content.replace(/[#*_~`>]/g, '').trim();
}

/**
 * Sanitize a title string for use as a filename.
 * @param {string} title
 * @returns {string}
 */
function sanitizeFilename(title) {
  return (title || 'InkForge-Document').replace(/[^a-zA-Z0-9\s-]/g, '').replace(/\s+/g, '-');
}

/**
 * Generate a PDF buffer from content.
 * @param {string} content
 * @param {string} title
 * @returns {Promise<Buffer>}
 */
async function generatePDF(content, title) {
  const PDFDocument = require('pdfkit');

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margin: 72,
      size: 'A4',
      info: {
        Title: title || 'InkForge Document',
        Author: 'InkForge AI Writing Assistant',
      },
    });

    const chunks = [];
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Title
    doc.font('Helvetica-Bold').fontSize(24).text(title || 'InkForge Document', {
      align: 'center',
    });
    doc.moveDown(0.5);
    doc.font('Helvetica').fontSize(10).fillColor('#888888')
      .text('Generated by InkForge AI Writing Assistant', { align: 'center' });
    doc.moveDown(1);
    doc.moveTo(72, doc.y).lineTo(523, doc.y).strokeColor('#e0e0e0').stroke();
    doc.moveDown(1);

    // Body
    const clean = cleanMarkdown(content);
    doc.fillColor('#333333').font('Helvetica').fontSize(12);
    const paragraphs = clean.split('\n\n');
    paragraphs.forEach((para, i) => {
      if (para.trim()) {
        doc.text(para.trim(), { align: 'justify', lineGap: 4 });
        if (i < paragraphs.length - 1) doc.moveDown(0.8);
      }
    });

    doc.end();
  });
}

/**
 * Generate a DOCX buffer from content.
 * @param {string} content
 * @param {string} title
 * @returns {Promise<Buffer>}
 */
async function generateDOCX(content, title) {
  const docx = require('docx');
  const clean = cleanMarkdown(content);
  const paragraphs = clean.split('\n\n').filter(p => p.trim());

  const doc = new docx.Document({
    sections: [{
      properties: {},
      children: [
        new docx.Paragraph({
          children: [new docx.TextRun({
            text: title || 'InkForge Document',
            bold: true, size: 48, font: 'Calibri',
          })],
          spacing: { after: 200 },
          alignment: docx.AlignmentType.CENTER,
        }),
        new docx.Paragraph({
          children: [new docx.TextRun({
            text: 'Generated by InkForge AI Writing Assistant',
            size: 20, color: '888888', font: 'Calibri',
          })],
          spacing: { after: 400 },
          alignment: docx.AlignmentType.CENTER,
        }),
        ...paragraphs.map(para => new docx.Paragraph({
          children: [new docx.TextRun({
            text: para.trim(), size: 24, font: 'Calibri',
          })],
          spacing: { after: 200, line: 360 },
        })),
      ],
    }],
  });

  return docx.Packer.toBuffer(doc);
}

/**
 * Generate a plain text string from content.
 * @param {string} content
 * @param {string} title
 * @returns {string}
 */
function generateTXT(content, title) {
  const clean = cleanMarkdown(content);
  return `${title || 'InkForge Document'}\n${'='.repeat(50)}\n\n${clean}\n\n${'='.repeat(50)}\nGenerated by InkForge AI Writing Assistant`;
}

module.exports = {
  generatePDF,
  generateDOCX,
  generateTXT,
  sanitizeFilename,
};
